import assert from 'node:assert/strict';
import {newRoom,buildDeck,apply,start,startQuiz,nextQuiz,playable,tick,publicState} from './onecard-engine.mjs';
const deck=buildDeck();
assert.equal(deck.length,80);assert.equal(deck.filter(c=>c.type==='normal').length,56);
assert.equal(new Set(deck.map(c=>c.id)).size,80);
let g=newRoom();apply(g,'u1',{type:'join',name:'하나',team:'A'},1);apply(g,'u2',{type:'join',name:'둘',team:'B'},1);
start(g,deck,100);assert.equal(g.players[0].hand.length,6);assert.equal(g.deck.length,67);
const publicData=publicState(g);assert.ok(!('deck' in publicData));assert.ok(!('hand' in publicData.players[0]));
g.target=120;assert.ok(playable(g,{type:'normal',code:420}));assert.ok(playable(g,{type:'normal',code:150}));assert.ok(!playable(g,{type:'normal',code:430}));
g.attack=5;g.attackLevel=3;assert.ok(playable(g,{type:'plus',value:3}));assert.ok(!playable(g,{type:'plus',value:2}));
assert.throws(()=>apply(g,'u2',{type:'draw',turnNo:g.turnNo},200));
g.attack=0;g.attackLevel=0;g.players[0].hand=[{id:'skip',type:'skip',code:'⊘',label:'스킵'},{id:'n',type:'normal',code:100}];
apply(g,'u1',{type:'play',cardId:'skip',turnNo:g.turnNo},300);
assert.ok(g.onePending);apply(g,'u1',{type:'one',turnNo:g.turnNo},400);assert.equal(g.turn,0); // 2인 스킵
g.players[0].hand=[{id:'n',type:'normal',code:100},{id:'n2',type:'normal',code:110}];
apply(g,'u1',{type:'play',cardId:'n',turnNo:g.turnNo},500);tick(g,3501);assert.equal(g.players[0].hand.length,2);assert.equal(g.turn,1);
g.players[1].hand=[{id:'joker',type:'joker',code:'★',label:'조커'},{id:'n3',type:'normal',code:300}];
g.attack=3;g.attackLevel=3;apply(g,'u2',{type:'play',cardId:'joker',target:800,turnNo:g.turnNo},4000);assert.equal(g.attack,0);assert.equal(g.target,800);
g=newRoom('team');for(let i=0;i<4;i++)apply(g,'u'+i,{type:'join',name:'팀원'+i,team:i<2?'A':'B'},1);
apply(g,'u1',{type:'team',team:'B'},2);assert.throws(()=>start(g,buildDeck(),10));apply(g,'u1',{type:'team',team:'A'},3);start(g,buildDeck(),10);tick(g,g.deadline);assert.equal(g.phase,'finished');assert.equal(g.winner,'무승부');
console.log('80장 덱, 비공개 손패, 배분, 자리 매칭, 공격 방어, 차례 검증, 스킵, 원카드 벌칙, 조커, 팀 선택, 시간 종료: PASS');
g=newRoom('individual',30,'quiz');
for(let i=0;i<20;i++)apply(g,'u'+i,{type:'join',name:'학생'+i,team:'A'},1);
assert.throws(()=>apply(g,'extra',{type:'join',name:'초과',team:'A'},1));
startQuiz(g,[{topic:'문학',options:['100','800'],answer:'800',explanation:'문학은 800'}],1000);
assert.equal(publicState(g).question.answer,undefined);
apply(g,'u0',{type:'answer',questionIndex:0,answer:'800'},2000);
assert.equal(g.players[0].score,138);assert.throws(()=>apply(g,'u0',{type:'answer',questionIndex:0,answer:'800'},2001));
tick(g,21000);assert.equal(publicState(g).question.answer,'800');nextQuiz(g,21001);assert.equal(g.winner,'학생0 승리');
console.log('실시간 퀴즈 20명 제한, 정답 비공개, 1회 제출, 속도 점수, 정답 공개, 순위 집계: PASS');
